// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBjEteTGCS66-CyNNh9zNXOojVmDiQeE0',
    appId: '1:763799238219:web:347a7bd3c54ffd5cc7bfce',
    messagingSenderId: '763799238219',
    projectId: 'flutter-update-bca2b',
    authDomain: 'flutter-update-bca2b.firebaseapp.com',
    databaseURL: 'https://flutter-update-bca2b-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-update-bca2b.appspot.com',
    measurementId: 'G-VGGVKP96JB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1fc11S_vpmfZWsF4eFtcUk-HQYyphyYk',
    appId: '1:763799238219:android:2ce135f927f05fa3c7bfce',
    messagingSenderId: '763799238219',
    projectId: 'flutter-update-bca2b',
    databaseURL: 'https://flutter-update-bca2b-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-update-bca2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtigSorZ3UmIGZzrno3AHgoaxkliILkGo',
    appId: '1:763799238219:ios:7c34b14df00a7537c7bfce',
    messagingSenderId: '763799238219',
    projectId: 'flutter-update-bca2b',
    databaseURL: 'https://flutter-update-bca2b-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-update-bca2b.appspot.com',
    iosBundleId: 'com.example.quantmhillAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtigSorZ3UmIGZzrno3AHgoaxkliILkGo',
    appId: '1:763799238219:ios:c39ca7793bb64033c7bfce',
    messagingSenderId: '763799238219',
    projectId: 'flutter-update-bca2b',
    databaseURL: 'https://flutter-update-bca2b-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-update-bca2b.appspot.com',
    iosBundleId: 'com.example.quantmhillAssignment.RunnerTests',
  );
}
